[package]
name = "fibers_rpc"
version = "0.3.4"
authors = ["Takeru Ohta <phjgt308@gmail.com>"]
description = "RPC library built on top of fibers crate"
homepage = "https://github.com/sile/fibers_rpc"
repository = "https://github.com/sile/fibers_rpc"
readme = "README.md"
keywords = ["rpc", "fibers"]
categories = ["network-programming", "asynchronous"]
license = "MIT"
edition = "2018"

[badges]
travis-ci = {repository = "sile/fibers_rpc"}
codecov = {repository = "sile/fibers_rpc"}

[dependencies]
atomic_immut = "0.1"
bytecodec = "0.4"
byteorder = "1"
factory = "0.1"
fibers = "0.1"
fibers_tasque = "0.1"
futures = "0.1"
futures03 = { package = "futures", version = "0.3" }
prometrics = "0.1"
slog = "2"
trackable = "0.2"
tokio = { version = "0.3", features = ["net", "stream"] }

[dev-dependencies]
clap = "2"
fibers_global = "0.1"
sloggers = "0.3"

[patch.crates-io]
fibers = { git = "https://github.com/dwango/fibers-rs", branch = "tmp/sync-delegates-to-futures-0.1" }